name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Gulp test
      run: yarn gulp
    - name: Unit tests
      run: yarn test:unit
    - name: Coverage test
      run: yarn test:unit:coverage
    - name: Lint test
      run: yarn test:lint
    - name: Size test
      run: yarn test:size
    - name: Lighthouse audit
      run: yarn test:audit
  
